name: Multi-Package Changelog

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'codeql-custom-queries-**' # Ne se déclenche que si un package change

jobs:
  generate-changelogs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Changelogs for each package
        uses: orhun/git-cliff-action@v4
        with:
          # On cherche tous les dossiers correspondants
          # et on génère un changelog pour chacun
          config: cliff.toml
          args: --verbose
        env:
          # Cette commande va générer les changelogs pour chaque dossier trouvé
          OUTPUT: "codeql-custom-queries-*/CHANGELOG.md"

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "**/CHANGELOG.md"
          git commit -m "chore: update package changelogs [skip ci]" || echo "No changes"
          git push