name: PR & Commit Validation

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  validate-conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: PR Title Validation
        if: github.event_name == 'pull_request'
        uses: ytanikin/pr-conventional-commits@1.4.0
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert"]'
          add_label: 'false'

      - name: Push Commit Message Validation
        if: github.event_name == 'push'
        uses: ytanikin/pr-conventional-commits@1.4.0
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert"]'
          add_label: 'false'