name: "CodeQL Analysis - Manual Build"

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'codeql-custom-queries-**/**'

jobs:
  analyze:
    name: Analyze Test Code
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - test_dir: 'codeql-custom-queries-java-test'
            language: 'java'
            local_queries: './codeql-custom-queries-java'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
        queries: ${{ matrix.local_queries }}

    - name: Manual Build for Java
      if: matrix.language == 'java'
      run: |
        echo "Compilation des fichiers Java dans ${{ matrix.test_dir }}..."
        find ${{ matrix.test_dir }} -name "*.java" > sources.txt
        if [ -s sources.txt ]; then
          javac @sources.txt
        else
          echo "Aucun fichier Java trouvé."
          exit 1
        fi

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{ matrix.language }}/dir:${{ matrix.test_dir }}"

    - name: Trigger Publish Workflow
      # On vérifie d'abord que l'analyse est un succès
      if: success()
      env:
        # On injecte le secret dans une variable d'environnement
        PUBLISH_TOKEN: ${{ secrets.PACK_PUBLISH_TOKEN }}
        GH_TOKEN: ${{ github.token }}
      run: |
        if [ -z "$PUBLISH_TOKEN" ]; then
          echo "Le secret PACK_PUBLISH_TOKEN est manquant. Saut de la publication."
          exit 0
        fi

        echo "Tests réussis et token détecté. Déclenchement de la publication..."
        gh workflow run "Publish Changed CodeQL Packs" --ref main
