name: "CodeQL Analysis - Manual Build"

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'codeql-custom-queries-**/**'

jobs:
  analyze:
    name: Analyze Test Code
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - test_dir: 'codeql-custom-queries-java-test'
            language: 'java'
            local_queries: './codeql-custom-queries-java'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
        queries: ${{ matrix.local_queries }}

    - name: Manual Build for Java
      if: matrix.language == 'java'
      run: |
        echo "Compilation des fichiers Java dans ${{ matrix.test_dir }}..."
        find ${{ matrix.test_dir }} -name "*.java" > sources.txt
        if [ -s sources.txt ]; then
          javac @sources.txt
        else
          echo "Aucun fichier Java trouvé."
          exit 1
        fi

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{ matrix.language }}/dir:${{ matrix.test_dir }}"

    - name: Trigger Publish Workflow
      # On vérifie le succès de l'analyse ET la présence du token
      if: success() && secrets.PACK_PUBLISH_TOKEN != ''
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        echo "Tests réussis et token présent. Déclenchement de la publication..."
        gh workflow run "Publish Changed CodeQL Packs" --ref main
