name: "CodeQL Unitary Analysis - Java"

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'codeql-custom-queries-java/**'
      - 'codeql-custom-queries-java-test/**'

jobs:
  analyze:
    name: Analyze Java Custom Queries
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v4
      with:
        languages: java
        queries: ./codeql-custom-queries-java

    - name: Manual Build (Java Test Files)
      run: |
        echo "Compilation des fichiers Java dans codeql-custom-queries-java-test..."
        find codeql-custom-queries-java-test -name "*.java" > sources.txt
        if [ -s sources.txt ]; then
          javac @sources.txt
        else
          echo "Aucun fichier Java de test trouv√©."
          exit 1
        fi

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v4
      with:
        category: "/language:java/dir:codeql-custom-queries-java-test"
