name: "CodeQL Unitary Analysis - Python"

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'codeql-custom-queries-python/**'
      - 'codeql-custom-queries-python-test/**'

jobs:
  analyze:
    name: Analyze Python Custom Queries
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: python
        queries: ./codeql-custom-queries-python

    - name: Verify Python Test Files
      run: |
        echo "Vérification des fichiers Python dans codeql-custom-queries-python-test..."
        find codeql-custom-queries-python-test -name "*.py" > sources.txt
        if [ -s sources.txt ]; then
          echo "Fichiers trouvés, CodeQL va procéder à l'analyse."
        else
          echo "Aucun fichier Python de test trouvé."
          exit 1
        fi

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:python/dir:codeql-custom-queries-python-test"
